"""add soft delete deleted_at column

Revision ID: 08f455ef2e72
Revises: 7dc1cf0f32ec
Create Date: 2026-03-12 21:24:02.701191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f455ef2e72'
down_revision = '7dc1cf0f32ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
