"""add soft delete deleted_at column

Revision ID: 7dc1cf0f32ec
Revises: c299aac315d0
Create Date: 2026-03-12 21:22:20.974165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc1cf0f32ec'
down_revision = 'c299aac315d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'deleted_at')
    # ### end Alembic commands ###
